---

apt_packages:
  - awscli
  - build-essential
  - git
  - python3
  - ssh
  - ssh-client
  - vim
  - wget
  - zsh

docker_packages:
  - apt-transport-https
  - aptitude
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools

postgres_packages:
  - bash
  - openssl
  - libpq-dev
  - libssl-dev
  - libssl-doc
  - postgresql
  - postgresql-contrib
  - python3-psycopg2

user: ubuntu

db_user: ubuntu
db_name: ubuntu
db_password: ubuntu

docker_user: ubuntu

git_username: benmangold
git_email: benmangold@gmail.com
