---

- name: Setup default git configuration
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "{{ git_username }}" }
    - {name: "user.email", value: "{{ git_email }}" }
    - {name: "ui.color",   value: "True" }
  become: true
  become_user: "{{ user }}"
