---

- name: modify permissions and properties of a directory (or create it if it doesn't exist)
  file:
    path: /home/{{ user }}
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: modify permissions and properties of a directory (or create it if it doesn't exist)
  file:
    path: /home/{{ user }}/github
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
