---

- name: Update and Prune Packages
  apt:
    update_cache: yes
    upgrade: 'yes'
    autoremove: yes
    autoclean: yes

- name: Install Packages
  package:
    name: "{{ apt_packages }}"
    state: present

- name: Install Docker Packages
  package:
    name: "{{ docker_packages }}"
    state: present

- name: Install PostgreSQL Packages
  package:
    name: "{{ postgres_packages }}"
    state: present
