---
name: Build

on:
  push:
    branches:
      - main

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python_version: '3.6.9'

      - name: Install dependencies
        run: |
          pip install ansible
      - name: Packer build
        run: packer build ubuntu/ubuntu-ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
